hwi_oauth:
    firewall_names: [main]
    # https://github.com/hwi/HWIOAuthBundle/blob/master/docs/2-configuring_resource_owners.md
    resource_owners:
        azure:
            type:                azure
            client_id:           '%env(AZURE_ID)%'
            client_secret:       '%env(AZURE_SECRET)%'
            scope:               "openid profile User.Read"

            options:
                application: 
